// <auto-generated by="the Blazor I18n Text compiler" />
namespace BlazorIdiomas.Client.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"About"</summary>
        public string About;

        /// <summary>"Counter"</summary>
        public string Count;

        /// <summary>"Fetchdata"</summary>
        public string Fetchdata;

        /// <summary>"Hello World!"</summary>
        public string HelloWorld;

        /// <summary>"Home"</summary>
        public string Home;

        /// <summary>"World"</summary>
        public string World;
    }
}
